VILLAGE_TYPES = [
    "plains",
    "desert",
    "savanna",
    "taiga",
    "snowy"
]

ITEMS = {
    "Food": [
        {"name": "cooked_beef", "display": "Cooked Beef", "icon": "🥩"},
        {"name": "golden_carrot", "display": "Golden Carrot", "icon": "🥕"},
        {"name": "bread", "display": "Bread", "icon": "🍞"},
        {"name": "cooked_porkchop", "display": "Cooked Porkchop", "icon": "🍖"},
        {"name": "cooked_chicken", "display": "Cooked Chicken", "icon": "🍗"},
        {"name": "cooked_mutton", "display": "Cooked Mutton", "icon": "🥩"},
        {"name": "baked_potato", "display": "Baked Potato", "icon": "🥔"},
        {"name": "golden_apple", "display": "Golden Apple", "icon": "🍎"},
        {"name": "enchanted_golden_apple", "display": "God Apple", "icon": "✨"},
        {"name": "cooked_salmon", "display": "Cooked Salmon", "icon": "🐟"},
        {"name": "rabbit_stew", "display": "Rabbit Stew", "icon": "🥣"},
        {"name": "mushroom_stew", "display": "Mushroom Stew", "icon": "🍲"},
        {"name": "pumpkin_pie", "display": "Pumpkin Pie", "icon": "🥧"},
        {"name": "beetroot_soup", "display": "Beetroot Soup", "icon": "🥣"},
    ],
    "Weapons (power coded)": [
        {"name": "netherite_sword", "display": "⬛ Netherite Sword", "icon": "⚔️"},
        {"name": "diamond_sword", "display": "💎 Diamond Sword", "icon": "⚔️"},
        {"name": "trident", "display": "💠 Trident", "icon": "🔱"},
        {"name": "iron_sword", "display": "⚪ Iron Sword", "icon": "⚔️"},
        {"name": "stone_sword", "display": "⬛ Stone Sword", "icon": "⚔️"},
        {"name": "golden_sword", "display": "🟡 Golden Sword", "icon": "⚔️"},
        {"name": "wooden_sword", "display": "🟤 Wooden Sword", "icon": "⚔️"},
        {"name": "crossbow", "display": "🟦 Crossbow", "icon": "🏹"},
        {"name": "bow", "display": "🟩 Bow", "icon": "🏹"},
        {"name": "fire_charge", "display": "🔥 Fire Charge", "icon": "🔥"},
    ],
    "Tools - Netherite": [
        {"name": "netherite_pickaxe", "display": "⬛ Netherite Pickaxe", "icon": "⛏️"},
        {"name": "netherite_axe", "display": "⬛ Netherite Axe", "icon": "🪓"},
        {"name": "netherite_shovel", "display": "⬛ Netherite Shovel", "icon": "🛠️"},
        {"name": "netherite_hoe", "display": "⬛ Netherite Hoe", "icon": "🔧"},
    ],
    "Tools - Diamond": [
        {"name": "diamond_pickaxe", "display": "💎 Diamond Pickaxe", "icon": "⛏️"},
        {"name": "diamond_axe", "display": "💎 Diamond Axe", "icon": "🪓"},
        {"name": "diamond_shovel", "display": "💎 Diamond Shovel", "icon": "🔨"},
        {"name": "diamond_hoe", "display": "💎 Diamond Hoe", "icon": "🔧"},
    ],
    "Tools - Iron": [
        {"name": "iron_pickaxe", "display": "⚪ Iron Pickaxe", "icon": "⛏️"},
        {"name": "iron_axe", "display": "⚪ Iron Axe", "icon": "🪓"},
        {"name": "iron_shovel", "display": "⚪ Iron Shovel", "icon": "🛠️"},
        {"name": "iron_hoe", "display": "⚪ Iron Hoe", "icon": "🔧"},
    ],
    "Tools - Stone": [
        {"name": "stone_pickaxe", "display": "⬛ Stone Pickaxe", "icon": "⛏️"},
        {"name": "stone_axe", "display": "⬛ Stone Axe", "icon": "🪓"},
        {"name": "stone_shovel", "display": "⬛ Stone Shovel", "icon": "🛠️"},
        {"name": "stone_hoe", "display": "⬛ Stone Hoe", "icon": "🔧"},
    ],
    "Tools - Gold": [
        {"name": "golden_pickaxe", "display": "🟡 Golden Pickaxe", "icon": "⛏️"},
        {"name": "golden_axe", "display": "🟡 Golden Axe", "icon": "🪓"},
        {"name": "golden_shovel", "display": "🟡 Golden Shovel", "icon": "🛠️"},
        {"name": "golden_hoe", "display": "🟡 Golden Hoe", "icon": "🔧"},
    ],
    "Tools - Wood": [
        {"name": "wooden_pickaxe", "display": "🟤 Wooden Pickaxe", "icon": "⛏️"},
        {"name": "wooden_axe", "display": "🟤 Wooden Axe", "icon": "🪓"},
        {"name": "wooden_shovel", "display": "🟤 Wooden Shovel", "icon": "🛠️"},
        {"name": "wooden_hoe", "display": "🟤 Wooden Hoe", "icon": "🔧"},
    ],
    "Tools - Utility": [
        {"name": "fishing_rod", "display": "🪝 Fishing Rod", "icon": "🎣"},
        {"name": "shears", "display": "✂️ Shears", "icon": "✂️"},
        {"name": "flint_and_steel", "display": "🔥 Flint and Steel", "icon": "🔥"},
        {"name": "brush", "display": "🪥 Brush", "icon": "🪥"},
        {"name": "iron_shovel", "display": "⚪ Iron Shovel", "icon": "🛠️"},
    ],
    "Armor": [
        {"name": "diamond_helmet", "display": "Diamond Helmet", "icon": "⛑️"},
        {"name": "diamond_chestplate", "display": "Diamond Chestplate", "icon": "🦺"},
        {"name": "diamond_leggings", "display": "Diamond Leggings", "icon": "👖"},
        {"name": "diamond_boots", "display": "Diamond Boots", "icon": "👢"},
        {"name": "netherite_helmet", "display": "Netherite Helmet", "icon": "⛑️"},
        {"name": "netherite_chestplate", "display": "Netherite Chestplate", "icon": "🦺"},
        {"name": "netherite_leggings", "display": "Netherite Leggings", "icon": "👖"},
        {"name": "netherite_boots", "display": "Netherite Boots", "icon": "👢"},
        {"name": "elytra", "display": "Elytra", "icon": "🪽"},
    ],
    "Building - Wood Core": [
        {"name": "oak_planks", "display": "Oak Planks", "icon": "🪵"},
        {"name": "spruce_planks", "display": "Spruce Planks", "icon": "🪵"},
        {"name": "birch_planks", "display": "Birch Planks", "icon": "🪵"},
        {"name": "dark_oak_planks", "display": "Dark Oak Planks", "icon": "🪵"},
        {"name": "mangrove_planks", "display": "Mangrove Planks", "icon": "🪵"},
        {"name": "bamboo_planks", "display": "Bamboo Planks", "icon": "🪵"},
        {"name": "bamboo_mosaic", "display": "Bamboo Mosaic", "icon": "🟩"},
        {"name": "crimson_planks", "display": "Crimson Planks", "icon": "🪵"},
        {"name": "warped_planks", "display": "Warped Planks", "icon": "🪵"},
        {"name": "oak_log", "display": "Oak Log", "icon": "🪵"},
        {"name": "stripped_oak_log", "display": "Stripped Oak Log", "icon": "🪵"},
        {"name": "cherry_planks", "display": "Cherry Planks", "icon": "🌸"},
        {"name": "cherry_log", "display": "Cherry Log", "icon": "🌸"},
        {"name": "scaffolding", "display": "Scaffolding", "icon": "🪜"},
    ],
    "Building - Wood Stairs & Slabs": [
        {"name": "oak_stairs", "display": "Oak Stairs", "icon": "🪜"},
        {"name": "oak_slab", "display": "Oak Slab", "icon": "➖"},
        {"name": "spruce_stairs", "display": "Spruce Stairs", "icon": "🪜"},
        {"name": "spruce_slab", "display": "Spruce Slab", "icon": "➖"},
        {"name": "birch_stairs", "display": "Birch Stairs", "icon": "🪜"},
        {"name": "birch_slab", "display": "Birch Slab", "icon": "➖"},
        {"name": "dark_oak_stairs", "display": "Dark Oak Stairs", "icon": "🪜"},
        {"name": "dark_oak_slab", "display": "Dark Oak Slab", "icon": "➖"},
        {"name": "mangrove_stairs", "display": "Mangrove Stairs", "icon": "🪜"},
        {"name": "mangrove_slab", "display": "Mangrove Slab", "icon": "➖"},
        {"name": "bamboo_stairs", "display": "Bamboo Stairs", "icon": "🪜"},
        {"name": "bamboo_slab", "display": "Bamboo Slab", "icon": "➖"},
        {"name": "crimson_stairs", "display": "Crimson Stairs", "icon": "🪜"},
        {"name": "crimson_slab", "display": "Crimson Slab", "icon": "➖"},
        {"name": "warped_stairs", "display": "Warped Stairs", "icon": "🪜"},
        {"name": "warped_slab", "display": "Warped Slab", "icon": "➖"},
        {"name": "cherry_stairs", "display": "Cherry Stairs", "icon": "🪜"},
        {"name": "cherry_slab", "display": "Cherry Slab", "icon": "➖"},
    ],
    "Building - Wood Fences & Gates": [
        {"name": "oak_fence", "display": "Oak Fence", "icon": "🚧"},
        {"name": "oak_fence_gate", "display": "Oak Gate", "icon": "🚪"},
        {"name": "spruce_fence", "display": "Spruce Fence", "icon": "🚧"},
        {"name": "spruce_fence_gate", "display": "Spruce Gate", "icon": "🚪"},
        {"name": "birch_fence", "display": "Birch Fence", "icon": "🚧"},
        {"name": "birch_fence_gate", "display": "Birch Gate", "icon": "🚪"},
        {"name": "dark_oak_fence", "display": "Dark Oak Fence", "icon": "🚧"},
        {"name": "dark_oak_fence_gate", "display": "Dark Oak Gate", "icon": "🚪"},
        {"name": "mangrove_fence", "display": "Mangrove Fence", "icon": "🚧"},
        {"name": "mangrove_fence_gate", "display": "Mangrove Gate", "icon": "🚪"},
        {"name": "bamboo_fence", "display": "Bamboo Fence", "icon": "🚧"},
        {"name": "bamboo_fence_gate", "display": "Bamboo Gate", "icon": "🚪"},
        {"name": "crimson_fence", "display": "Crimson Fence", "icon": "🚧"},
        {"name": "crimson_fence_gate", "display": "Crimson Gate", "icon": "🚪"},
        {"name": "warped_fence", "display": "Warped Fence", "icon": "🚧"},
        {"name": "warped_fence_gate", "display": "Warped Gate", "icon": "🚪"},
        {"name": "cherry_fence", "display": "Cherry Fence", "icon": "🚧"},
        {"name": "cherry_fence_gate", "display": "Cherry Gate", "icon": "🚪"},
    ],
    "Building - Stone & Brick Core": [
        {"name": "stone", "display": "Stone", "icon": "🪨"},
        {"name": "smooth_stone", "display": "Smooth Stone", "icon": "⬜"},
        {"name": "cobblestone", "display": "Cobblestone", "icon": "⬛"},
        {"name": "stone_bricks", "display": "Stone Bricks", "icon": "🧱"},
        {"name": "deepslate", "display": "Deepslate", "icon": "⬛"},
        {"name": "polished_deepslate", "display": "Polished Deepslate", "icon": "⬛"},
        {"name": "bricks", "display": "Bricks", "icon": "🧱"},
        {"name": "polished_blackstone_bricks", "display": "Blackstone Bricks", "icon": "⬛"},
        {"name": "basalt", "display": "Basalt", "icon": "⚪"},
        {"name": "sandstone", "display": "Sandstone", "icon": "🟨"},
        {"name": "granite", "display": "Granite", "icon": "🟥"},
        {"name": "diorite", "display": "Diorite", "icon": "⬜"},
        {"name": "andesite", "display": "Andesite", "icon": "⬜"},
        {"name": "blackstone", "display": "Blackstone", "icon": "⬛"},
        {"name": "nether_bricks", "display": "Nether Bricks", "icon": "🟥"},
        {"name": "quartz_block", "display": "Quartz Block", "icon": "⬜"},
        {"name": "deepslate_tiles", "display": "Deepslate Tiles", "icon": "⬛"},
    ],
    "Building - Stone Stairs & Slabs": [
        {"name": "stone_stairs", "display": "Stone Stairs", "icon": "🪜"},
        {"name": "stone_slab", "display": "Stone Slab", "icon": "➖"},
        {"name": "cobblestone_stairs", "display": "Cobbled Stairs", "icon": "🪜"},
        {"name": "cobblestone_slab", "display": "Cobbled Slab", "icon": "➖"},
        {"name": "stone_brick_stairs", "display": "Stone Brick Stairs", "icon": "🪜"},
        {"name": "stone_brick_slab", "display": "Stone Brick Slab", "icon": "➖"},
        {"name": "sandstone_stairs", "display": "Sandstone Stairs", "icon": "🪜"},
        {"name": "sandstone_slab", "display": "Sandstone Slab", "icon": "➖"},
        {"name": "quartz_stairs", "display": "Quartz Stairs", "icon": "🪜"},
        {"name": "quartz_slab", "display": "Quartz Slab", "icon": "➖"},
        {"name": "polished_deepslate_stairs", "display": "Polished Deepslate Stairs", "icon": "🪜"},
        {"name": "polished_deepslate_slab", "display": "Polished Deepslate Slab", "icon": "➖"},
        {"name": "polished_blackstone_brick_stairs", "display": "Blackstone Stairs", "icon": "🪜"},
        {"name": "polished_blackstone_brick_slab", "display": "Blackstone Slab", "icon": "➖"},
        {"name": "deepslate_tile_stairs", "display": "Tile Stairs", "icon": "🪜"},
        {"name": "deepslate_tile_slab", "display": "Tile Slab", "icon": "➖"},
    ],
    "Building - Walls": [
        {"name": "cobblestone_wall", "display": "Cobbled Wall", "icon": "🧱"},
        {"name": "stone_brick_wall", "display": "Stone Brick Wall", "icon": "🧱"},
        {"name": "mossy_stone_brick_wall", "display": "Mossy Brick Wall", "icon": "🌿"},
        {"name": "deepslate_brick_wall", "display": "Deepslate Brick Wall", "icon": "⬛"},
        {"name": "polished_deepslate_wall", "display": "Polished Deepslate Wall", "icon": "⬛"},
        {"name": "blackstone_wall", "display": "Blackstone Wall", "icon": "⬛"},
        {"name": "nether_brick_wall", "display": "Nether Brick Wall", "icon": "🟥"},
    ],
    "Building Materials - Glass & Light": [
        {"name": "glass", "display": "Glass", "icon": "🔲"},
        {"name": "tinted_glass", "display": "Tinted Glass", "icon": "🟪"},
        {"name": "white_stained_glass", "display": "White Glass", "icon": "⬜"},
        {"name": "glass_pane", "display": "Glass Pane", "icon": "〰️"},
        {"name": "white_stained_glass_pane", "display": "White Pane", "icon": "〰️"},
        {"name": "glowstone", "display": "Glowstone", "icon": "✨"},
        {"name": "sea_lantern", "display": "Sea Lantern", "icon": "💡"},
        {"name": "shroomlight", "display": "Shroomlight", "icon": "🟠"},
        {"name": "lantern", "display": "Lantern", "icon": "🏮"},
        {"name": "soul_lantern", "display": "Soul Lantern", "icon": "💙"},
        {"name": "redstone_lamp", "display": "Redstone Lamp", "icon": "💡"},
        {"name": "end_rod", "display": "End Rod", "icon": "🧪"},
    ],

    "Building Materials - Decorative": [
        {"name": "white_concrete", "display": "White Concrete", "icon": "⬜"},
        {"name": "blue_concrete", "display": "Blue Concrete", "icon": "🟦"},
        {"name": "terracotta", "display": "Terracotta", "icon": "🟫"},
        {"name": "white_terracotta", "display": "White Terracotta", "icon": "🤍"},
        {"name": "prismarine", "display": "Prismarine", "icon": "🟩"},
        {"name": "dark_prismarine", "display": "Dark Prismarine", "icon": "🟩"},
        {"name": "polished_basalt", "display": "Polished Basalt", "icon": "⚪"},
    ],
    "Utilities": [
        {"name": "torch", "display": "Torch", "icon": "🔥"},
        {"name": "compass", "display": "Compass", "icon": "🧭"},
        {"name": "map", "display": "Map", "icon": "🗺️"},
        {"name": "spyglass", "display": "Spyglass", "icon": "🔭"},
        {"name": "shield", "display": "Shield", "icon": "🛡️"},
        {"name": "ender_pearl", "display": "Ender Pearl", "icon": "🔮"},
        {"name": "water_bucket", "display": "Water Bucket", "icon": "🪣"},
        {"name": "lava_bucket", "display": "Lava Bucket", "icon": "🪣"},
        {"name": "milk_bucket", "display": "Milk Bucket", "icon": "🥛"},
        {"name": "oak_boat", "display": "Boat", "icon": "⛵"},
        {"name": "bed", "display": "Bed", "icon": "🛏️"},
        {"name": "chest", "display": "Chest", "icon": "📦"},
        {"name": "crafting_table", "display": "Crafting Table", "icon": "🔨"},
        {"name": "furnace", "display": "Furnace", "icon": "🔥"},
        {"name": "anvil", "display": "Anvil", "icon": "⚒️"},
        {"name": "enchanting_table", "display": "Enchanting Table", "icon": "📖"},
        {"name": "ender_chest", "display": "Ender Chest", "icon": "📦"},
        {"name": "shulker_box", "display": "Shulker Box", "icon": "📦"},
        {"name": "campfire", "display": "Campfire", "icon": "🔥"},
        {"name": "hopper", "display": "Hopper", "icon": "🪣"},
        {"name": "observer", "display": "Observer", "icon": "👁️"},
        {"name": "piston", "display": "Piston", "icon": "📦"},
        {"name": "rail", "display": "Rail", "icon": "🛤️"},
        {"name": "lead", "display": "Lead", "icon": "🤝"},
    ],
    "Resources (rare -> common)": [
        {"name": "netherite_ingot", "display": "Netherite Ingot", "icon": "⬛"},
        {"name": "netherite_scrap", "display": "Netherite Scrap", "icon": "⬛"},
        {"name": "ancient_debris", "display": "Ancient Debris", "icon": "🟤"},
        {"name": "diamond", "display": "Diamond", "icon": "💎"},
        {"name": "emerald", "display": "Emerald", "icon": "💚"},
        {"name": "gold_ingot", "display": "Gold Ingot", "icon": "🟡"},
        {"name": "iron_ingot", "display": "Iron Ingot", "icon": "⚪"},
        {"name": "copper_ingot", "display": "Copper Ingot", "icon": "🟠"},
        {"name": "redstone", "display": "Redstone", "icon": "🔴"},
        {"name": "lapis_lazuli", "display": "Lapis Lazuli", "icon": "🔵"},
        {"name": "quartz", "display": "Quartz", "icon": "⬜"},
        {"name": "amethyst_shard", "display": "Amethyst Shard", "icon": "💜"},
        {"name": "raw_gold", "display": "Raw Gold", "icon": "🟡"},
        {"name": "raw_iron", "display": "Raw Iron", "icon": "⚪"},
        {"name": "raw_copper", "display": "Raw Copper", "icon": "🟠"},
        {"name": "coal", "display": "Coal", "icon": "⚫"},
        {"name": "charcoal", "display": "Charcoal", "icon": "⚫"},
        {"name": "slime_ball", "display": "Slime Ball", "icon": "🟢"},
        {"name": "blaze_rod", "display": "Blaze Rod", "icon": "🔥"},
        {"name": "ender_pearl", "display": "Ender Pearl", "icon": "🔮"},
        {"name": "ender_eye", "display": "Eye of Ender", "icon": "👁️"},
        {"name": "ghast_tear", "display": "Ghast Tear", "icon": "💧"},
        {"name": "magma_cream", "display": "Magma Cream", "icon": "🟠"},
        {"name": "phantom_membrane", "display": "Phantom Membrane", "icon": "🪽"},
        {"name": "string", "display": "String", "icon": "🧵"},
        {"name": "gunpowder", "display": "Gunpowder", "icon": "💥"},
    ],
    "Potions & Enchantments": [
        {"name": "potion{Potion:\"minecraft:healing\"}", "display": "Healing Potion", "icon": "❤️"},
        {"name": "potion{Potion:\"minecraft:strong_healing\"}", "display": "Strong Healing", "icon": "💗"},
        {"name": "potion{Potion:\"minecraft:regeneration\"}", "display": "Regeneration", "icon": "💚"},
        {"name": "potion{Potion:\"minecraft:swiftness\"}", "display": "Swiftness", "icon": "💨"},
        {"name": "potion{Potion:\"minecraft:strength\"}", "display": "Strength", "icon": "💪"},
        {"name": "potion{Potion:\"minecraft:fire_resistance\"}", "display": "Fire Resistance", "icon": "🔥"},
        {"name": "potion{Potion:\"minecraft:night_vision\"}", "display": "Night Vision", "icon": "👁️"},
        {"name": "enchanted_book", "display": "Enchanted Book", "icon": "📕"},
        {"name": "experience_bottle", "display": "XP Bottle", "icon": "✨"},
        {"name": "potion{Potion:\"minecraft:slow_falling\"}", "display": "Slow Falling", "icon": "🪽"},
        {"name": "potion{Potion:\"minecraft:water_breathing\"}", "display": "Water Breathing", "icon": "💧"},
        {"name": "potion{Potion:\"minecraft:leaping\"}", "display": "Jump Boost", "icon": "🦘"},
        {"name": "potion{Potion:\"minecraft:turtle_master\"}", "display": "Turtle Master", "icon": "🐢"},
    ],
    "Special": [
        {"name": "totem_of_undying", "display": "Totem of Undying", "icon": "✨"},
        {"name": "nether_star", "display": "Nether Star", "icon": "⭐"},
        {"name": "dragon_egg", "display": "Dragon Egg", "icon": "🥚"},
        {"name": "beacon", "display": "Beacon", "icon": "🔆"},
        {"name": "conduit", "display": "Conduit", "icon": "💠"},
        {"name": "heart_of_the_sea", "display": "Heart of the Sea", "icon": "💙"},
        {"name": "music_disc_cat", "display": "Music Disc", "icon": "💿"},
        {"name": "saddle", "display": "Saddle", "icon": "🏇"},
        {"name": "name_tag", "display": "Name Tag", "icon": "🏷️"},
        {"name": "elytra", "display": "Elytra", "icon": "🪽"},
        {"name": "goat_horn", "display": "Goat Horn", "icon": "📯"},
    ],
    "Arrows & Ammo": [
        {"name": "arrow", "display": "Arrow", "icon": "➡️"},
        {"name": "spectral_arrow", "display": "Spectral Arrow", "icon": "✨"},
        {"name": "tipped_arrow{Potion:\"minecraft:poison\"}", "display": "Poison Arrow", "icon": "☠️"},
        {"name": "firework_rocket", "display": "Firework", "icon": "🎆"},
        {"name": "tipped_arrow{Potion:\"minecraft:slow_falling\"}", "display": "Slow Falling Arrow", "icon": "🪽"},
        {"name": "tipped_arrow{Potion:\"minecraft:weakness\"}", "display": "Weakness Arrow", "icon": "💤"},
    ],
    "Flowers & Plants": [
        {"name": "dandelion", "display": "Dandelion", "icon": "🌼"},
        {"name": "poppy", "display": "Poppy", "icon": "🌺"},
        {"name": "blue_orchid", "display": "Blue Orchid", "icon": "💙"},
        {"name": "allium", "display": "Allium", "icon": "🌸"},
        {"name": "azure_bluet", "display": "Azure Bluet", "icon": "🤍"},
        {"name": "red_tulip", "display": "Red Tulip", "icon": "🌷"},
        {"name": "orange_tulip", "display": "Orange Tulip", "icon": "🧡"},
        {"name": "white_tulip", "display": "White Tulip", "icon": "🤍"},
        {"name": "pink_tulip", "display": "Pink Tulip", "icon": "💗"},
        {"name": "oxeye_daisy", "display": "Oxeye Daisy", "icon": "🌼"},
        {"name": "cornflower", "display": "Cornflower", "icon": "💙"},
        {"name": "lily_of_the_valley", "display": "Lily of the Valley", "icon": "🤍"},
        {"name": "sunflower", "display": "Sunflower", "icon": "🌻"},
        {"name": "lilac", "display": "Lilac", "icon": "💜"},
        {"name": "rose_bush", "display": "Rose Bush", "icon": "🌹"},
        {"name": "peony", "display": "Peony", "icon": "🌸"},
        {"name": "wither_rose", "display": "Wither Rose", "icon": "🖤"},
        {"name": "lily_pad", "display": "Lily Pad", "icon": "🍃"},
        {"name": "bamboo", "display": "Bamboo", "icon": "🎋"},
        {"name": "cactus", "display": "Cactus", "icon": "🌵"},
        {"name": "sugar_cane", "display": "Sugar Cane", "icon": "🎋"},
        {"name": "vine", "display": "Vine", "icon": "🌿"},
        {"name": "fern", "display": "Fern", "icon": "🌿"},
        {"name": "large_fern", "display": "Large Fern", "icon": "🌿"},
        {"name": "grass", "display": "Grass", "icon": "🌱"},
        {"name": "tall_grass", "display": "Tall Grass", "icon": "🌾"},
        {"name": "dead_bush", "display": "Dead Bush", "icon": "🥀"},
        {"name": "seagrass", "display": "Seagrass", "icon": "🌿"},
        {"name": "kelp", "display": "Kelp", "icon": "🌿"},
        {"name": "moss_block", "display": "Moss Block", "icon": "🟢"},
        {"name": "moss_carpet", "display": "Moss Carpet", "icon": "🟢"},
        {"name": "glow_berries", "display": "Glow Berries", "icon": "🫐"},
    ],
    "Seeds & Farming": [
        {"name": "wheat_seeds", "display": "Wheat Seeds", "icon": "🌾"},
        {"name": "wheat", "display": "Wheat", "icon": "🌾"},
        {"name": "beetroot_seeds", "display": "Beetroot Seeds", "icon": "🌱"},
        {"name": "beetroot", "display": "Beetroot", "icon": "🔴"},
        {"name": "melon_seeds", "display": "Melon Seeds", "icon": "🌱"},
        {"name": "melon_slice", "display": "Melon Slice", "icon": "🍉"},
        {"name": "pumpkin_seeds", "display": "Pumpkin Seeds", "icon": "🌱"},
        {"name": "pumpkin", "display": "Pumpkin", "icon": "🎃"},
        {"name": "carved_pumpkin", "display": "Carved Pumpkin", "icon": "🎃"},
        {"name": "carrot", "display": "Carrot", "icon": "🥕"},
        {"name": "potato", "display": "Potato", "icon": "🥔"},
        {"name": "poisonous_potato", "display": "Poisonous Potato", "icon": "☠️"},
        {"name": "sweet_berries", "display": "Sweet Berries", "icon": "🫐"},
        {"name": "cocoa_beans", "display": "Cocoa Beans", "icon": "🫘"},
        {"name": "sugar", "display": "Sugar", "icon": "🧂"},
        {"name": "nether_wart", "display": "Nether Wart", "icon": "🔴"},
        {"name": "torchflower_seeds", "display": "Torchflower Seeds", "icon": "🌱"},
        {"name": "torchflower", "display": "Torchflower", "icon": "🔥"},
        {"name": "pitcher_pod", "display": "Pitcher Pod", "icon": "🌱"},
        {"name": "pitcher_plant", "display": "Pitcher Plant", "icon": "🌺"},
        {"name": "bone_meal", "display": "Bone Meal", "icon": "🦴"},
        {"name": "composter", "display": "Composter", "icon": "♻️"},
    ],
    "Dyes": [
        {"name": "white_dye", "display": "White Dye", "icon": "⚪"},
        {"name": "light_gray_dye", "display": "Light Gray Dye", "icon": "◽"},
        {"name": "gray_dye", "display": "Gray Dye", "icon": "◾"},
        {"name": "black_dye", "display": "Black Dye", "icon": "⚫"},
        {"name": "red_dye", "display": "Red Dye", "icon": "🔴"},
        {"name": "orange_dye", "display": "Orange Dye", "icon": "🟠"},
        {"name": "yellow_dye", "display": "Yellow Dye", "icon": "🟡"},
        {"name": "lime_dye", "display": "Lime Dye", "icon": "🟢"},
        {"name": "green_dye", "display": "Green Dye", "icon": "🟩"},
        {"name": "cyan_dye", "display": "Cyan Dye", "icon": "🔷"},
        {"name": "light_blue_dye", "display": "Light Blue Dye", "icon": "💠"},
        {"name": "blue_dye", "display": "Blue Dye", "icon": "🔵"},
        {"name": "purple_dye", "display": "Purple Dye", "icon": "🟣"},
        {"name": "magenta_dye", "display": "Magenta Dye", "icon": "🩷"},
        {"name": "pink_dye", "display": "Pink Dye", "icon": "🌸"},
        {"name": "brown_dye", "display": "Brown Dye", "icon": "🟤"},
    ],
    "Wool & Carpet": [
        {"name": "white_wool", "display": "White Wool", "icon": "⬜"},
        {"name": "light_gray_wool", "display": "Light Gray Wool", "icon": "◽"},
        {"name": "gray_wool", "display": "Gray Wool", "icon": "◾"},
        {"name": "black_wool", "display": "Black Wool", "icon": "⬛"},
        {"name": "red_wool", "display": "Red Wool", "icon": "🟥"},
        {"name": "orange_wool", "display": "Orange Wool", "icon": "🟧"},
        {"name": "yellow_wool", "display": "Yellow Wool", "icon": "🟨"},
        {"name": "lime_wool", "display": "Lime Wool", "icon": "🟩"},
        {"name": "green_wool", "display": "Green Wool", "icon": "🟩"},
        {"name": "cyan_wool", "display": "Cyan Wool", "icon": "🟦"},
        {"name": "light_blue_wool", "display": "Light Blue Wool", "icon": "💙"},
        {"name": "blue_wool", "display": "Blue Wool", "icon": "🟦"},
        {"name": "purple_wool", "display": "Purple Wool", "icon": "🟪"},
        {"name": "magenta_wool", "display": "Magenta Wool", "icon": "🩷"},
        {"name": "pink_wool", "display": "Pink Wool", "icon": "🌸"},
        {"name": "brown_wool", "display": "Brown Wool", "icon": "🟫"},
        {"name": "white_carpet", "display": "White Carpet", "icon": "⬜"},
        {"name": "red_carpet", "display": "Red Carpet", "icon": "🟥"},
        {"name": "blue_carpet", "display": "Blue Carpet", "icon": "🟦"},
    ],
    "Doors & Trapdoors": [
        {"name": "oak_door", "display": "Oak Door", "icon": "🚪"},
        {"name": "spruce_door", "display": "Spruce Door", "icon": "🚪"},
        {"name": "birch_door", "display": "Birch Door", "icon": "🚪"},
        {"name": "jungle_door", "display": "Jungle Door", "icon": "🚪"},
        {"name": "acacia_door", "display": "Acacia Door", "icon": "🚪"},
        {"name": "dark_oak_door", "display": "Dark Oak Door", "icon": "🚪"},
        {"name": "mangrove_door", "display": "Mangrove Door", "icon": "🚪"},
        {"name": "cherry_door", "display": "Cherry Door", "icon": "🚪"},
        {"name": "bamboo_door", "display": "Bamboo Door", "icon": "🚪"},
        {"name": "crimson_door", "display": "Crimson Door", "icon": "🚪"},
        {"name": "warped_door", "display": "Warped Door", "icon": "🚪"},
        {"name": "iron_door", "display": "Iron Door", "icon": "🚪"},
        {"name": "oak_trapdoor", "display": "Oak Trapdoor", "icon": "🪟"},
        {"name": "spruce_trapdoor", "display": "Spruce Trapdoor", "icon": "🪟"},
        {"name": "birch_trapdoor", "display": "Birch Trapdoor", "icon": "🪟"},
        {"name": "jungle_trapdoor", "display": "Jungle Trapdoor", "icon": "🪟"},
        {"name": "acacia_trapdoor", "display": "Acacia Trapdoor", "icon": "🪟"},
        {"name": "dark_oak_trapdoor", "display": "Dark Oak Trapdoor", "icon": "🪟"},
        {"name": "mangrove_trapdoor", "display": "Mangrove Trapdoor", "icon": "🪟"},
        {"name": "cherry_trapdoor", "display": "Cherry Trapdoor", "icon": "🪟"},
        {"name": "bamboo_trapdoor", "display": "Bamboo Trapdoor", "icon": "🪟"},
        {"name": "crimson_trapdoor", "display": "Crimson Trapdoor", "icon": "🪟"},
        {"name": "warped_trapdoor", "display": "Warped Trapdoor", "icon": "🪟"},
        {"name": "iron_trapdoor", "display": "Iron Trapdoor", "icon": "🪟"},
    ],
    "Books & Paper": [
        {"name": "book", "display": "Book", "icon": "📕"},
        {"name": "writable_book", "display": "Book and Quill", "icon": "📖"},
        {"name": "written_book", "display": "Written Book", "icon": "📘"},
        {"name": "enchanted_book", "display": "Enchanted Book", "icon": "📗"},
        {"name": "paper", "display": "Paper", "icon": "📄"},
        {"name": "bookshelf", "display": "Bookshelf", "icon": "📚"},
        {"name": "lectern", "display": "Lectern", "icon": "📖"},
    ],
    "Redstone Components": [
        {"name": "redstone", "display": "Redstone Dust", "icon": "🔴"},
        {"name": "redstone_torch", "display": "Redstone Torch", "icon": "🔦"},
        {"name": "redstone_block", "display": "Redstone Block", "icon": "🟥"},
        {"name": "repeater", "display": "Repeater", "icon": "🔁"},
        {"name": "comparator", "display": "Comparator", "icon": "⚖️"},
        {"name": "lever", "display": "Lever", "icon": "🎚️"},
        {"name": "stone_button", "display": "Stone Button", "icon": "⏺️"},
        {"name": "oak_button", "display": "Oak Button", "icon": "⏺️"},
        {"name": "stone_pressure_plate", "display": "Stone Pressure Plate", "icon": "⬜"},
        {"name": "oak_pressure_plate", "display": "Oak Pressure Plate", "icon": "🟫"},
        {"name": "heavy_weighted_pressure_plate", "display": "Heavy Pressure Plate", "icon": "⚪"},
        {"name": "light_weighted_pressure_plate", "display": "Light Pressure Plate", "icon": "🟡"},
        {"name": "tripwire_hook", "display": "Tripwire Hook", "icon": "🪝"},
        {"name": "daylight_detector", "display": "Daylight Detector", "icon": "☀️"},
        {"name": "observer", "display": "Observer", "icon": "👁️"},
        {"name": "dropper", "display": "Dropper", "icon": "📤"},
        {"name": "dispenser", "display": "Dispenser", "icon": "📤"},
        {"name": "piston", "display": "Piston", "icon": "🔧"},
        {"name": "sticky_piston", "display": "Sticky Piston", "icon": "🔧"},
        {"name": "tnt", "display": "TNT", "icon": "💣"},
        {"name": "note_block", "display": "Note Block", "icon": "🎵"},
    ],
    "Brewing & Alchemy": [
        {"name": "brewing_stand", "display": "Brewing Stand", "icon": "⚗️"},
        {"name": "blaze_powder", "display": "Blaze Powder", "icon": "🔥"},
        {"name": "fermented_spider_eye", "display": "Fermented Spider Eye", "icon": "👁️"},
        {"name": "glistering_melon_slice", "display": "Glistering Melon", "icon": "✨"},
        {"name": "golden_carrot", "display": "Golden Carrot", "icon": "🥕"},
        {"name": "magma_cream", "display": "Magma Cream", "icon": "🟠"},
        {"name": "spider_eye", "display": "Spider Eye", "icon": "🕷️"},
        {"name": "pufferfish", "display": "Pufferfish", "icon": "🐡"},
        {"name": "rabbit_foot", "display": "Rabbit's Foot", "icon": "🐰"},
        {"name": "turtle_helmet", "display": "Turtle Helmet", "icon": "🐢"},
        {"name": "dragon_breath", "display": "Dragon's Breath", "icon": "💨"},
        {"name": "glass_bottle", "display": "Glass Bottle", "icon": "🍶"},
        {"name": "cauldron", "display": "Cauldron", "icon": "🫕"},
    ],
    "Mob Drops & Animal Items": [
        {"name": "leather", "display": "Leather", "icon": "🟫"},
        {"name": "feather", "display": "Feather", "icon": "🪶"},
        {"name": "bone", "display": "Bone", "icon": "🦴"},
        {"name": "spider_eye", "display": "Spider Eye", "icon": "🕷️"},
        {"name": "rotten_flesh", "display": "Rotten Flesh", "icon": "🧟"},
        {"name": "egg", "display": "Egg", "icon": "🥚"},
        {"name": "ink_sac", "display": "Ink Sac", "icon": "⚫"},
        {"name": "glow_ink_sac", "display": "Glow Ink Sac", "icon": "✨"},
        {"name": "rabbit_hide", "display": "Rabbit Hide", "icon": "🐰"},
        {"name": "rabbit_foot", "display": "Rabbit's Foot", "icon": "🐾"},
        {"name": "prismarine_shard", "display": "Prismarine Shard", "icon": "💎"},
        {"name": "prismarine_crystals", "display": "Prismarine Crystals", "icon": "💠"},
        {"name": "scute", "display": "Scute", "icon": "🐢"},
        {"name": "nautilus_shell", "display": "Nautilus Shell", "icon": "🐚"},
        {"name": "honeycomb", "display": "Honeycomb", "icon": "🍯"},
        {"name": "honey_bottle", "display": "Honey Bottle", "icon": "🍯"},
        {"name": "bee_nest", "display": "Bee Nest", "icon": "🐝"},
        {"name": "beehive", "display": "Beehive", "icon": "🐝"},
    ],
}
